sonar.projectKey=movie-api
sonar.projectName=movie-api
sonar.sources=app,config,database,routes,resources
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/build/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.qualitygate.wait=true
